[tool.poetry]
name = "sentry-proxy"
version = "0.1.0"
description = ""
authors = []
maintainers = []

[tool.poetry.dependencies]
python = "^3.9"
sentry-sdk = "^1.13.0"
proxy-py = "^2.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
